#!/usr/bin/python
import sys
from helper.db import DB
import migration
import model
import seeder
import config
import env
import os
from helper import tableit

command = sys.argv

# connect to database
db, cursor = config.connection.connect()
# end connect to database


def get_all_table():
    sql = f"SELECT table_name FROM information_schema.tables WHERE table_schema = '{env.db_name}'"
    cursor.execute(sql)
    fetch = cursor.fetchall()
    result = []
    for i in fetch:
        result.append(i[0])
    return result


if(command[1] == "run"):
    print("Executing application")
    os.system("py app.py")

# drop table
elif(command[1] == "drop"):
    print(f"Dropping table {command[2].lower()}")
    sql = migration.drop(command[2])
    cursor.execute(sql)
    db.commit()
    print(f"Table {command[2].lower()} has been dropped")

elif(command[1] == "drop:all"):
    table = get_all_table()
    for i in table:
        sql = "DROP TABLE " + i
        cursor.execute(sql)
        db.commit()
    print(f"All table has been dropped")
# end drop table

# create table
elif(command[1] == "migrate"):
    print(f"Migrating table {command[2].lower()}")
    sql = migration.migrate(command[2])
    cursor.execute(sql)
    db.commit()
    print(f"Table {command[2].lower()} has been migrated")


elif(command[1] == "migrate:all"):
    for i in range(len(migration.migrate_all())):
        sql = migration.migrate_all()[i]
        cursor.execute(sql)
        db.commit()
    print(f"All table has been migrated")
# end create table

# fresh database drop and migrate table
elif(command[1] == "migrate:fresh"):
    table = get_all_table()
    for i in table:
        sql = "DROP TABLE " + i
        cursor.execute(sql)
        db.commit()
    print(f"All table has been dropped")
    for i in range(len(migration.migrate_all())):
        sql = migration.migrate_all()[i]
        cursor.execute(sql)
        db.commit()
    print(f"All table has been migrated")
# end fresh database

# make new model
elif(command[1] == "make:model"):
    print(f"Creating model {command[2].lower()}")
    model.make_model(command[2])
    print(f"Model {command[2].lower()} has been make")
# end make new model

# make new migration
elif(command[1] == "make:migration"):
    print(f"Creating migration {command[2].lower()}")
    migration.make_migration(command[2])
    print(f"Migration {command[2].lower()} has been make")
# end make new migration

# make new seeder
elif(command[1] == "make:seeder"):
    print(f"Creating seeder {command[2].lower()}")
    seeder.make_seeder(command[2])
    print(f"Seeder {command[2].lower()} has been make")
# end make new seeder

elif(command[1] == "make:msm"):
    print(f"Creating model {command[2].lower()}")
    model.make_model(command[2])
    print(f"Model {command[2].lower()} has been make")
    print(f"Creating migration {command[2].lower()}")
    migration.make_migration(command[2])
    print(f"Migration {command[2].lower()} has been make")
    print(f"Creating seeder {command[2].lower()}")
    seeder.make_seeder(command[2])
    print(f"Seeder {command[2].lower()} has been make")


elif(command[1] == "seed:all"):
    seeder.seed_all()
    print(f"All seeder has been seeded")

elif(command[1] == "db:table"):
    query = "SELECT * FROM " + command[2]
    cursor.execute(query)
    # get field name
    field_name = [i[0] for i in cursor.description]
    fetch = cursor.fetchall()

    # print field name
    for i in field_name:
        print(i, end="\t")
    print()

    for i in fetch:
        print("{}".format(
            '\t'.join('{}'.format(i[k]) for k in range(len(i)))))

else:
    print("Command not found")


if("-s" in command):
    seeder.seed_all()
    print(f"All seeder has been seeded")
